name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.5
  PROJECT_PATH: .

jobs:
  export:
    name: Export ${{ matrix.name }}
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    strategy:
      matrix:
        include:
          - name: "Windows Desktop"
            path: "windows"
            exportName: "IdleBlockadeBreaker.exe"
            artifactName: "windows"
          - name: "Linux"
            path: "linux"
            exportName: "IdleBlockadeBreaker.x86_64"
            artifactName: "linux"
          - name: "macOS"
            path: "mac"
            exportName: "IdleBlockadeBreaker.zip"
            artifactName: "mac"
          - name: "Web"
            path: "web"
            exportName: "index.html"
            artifactName: "web"  
    container:
      image: barichello/godot-ci:4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.path }}
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release  "${{ matrix.name }}" "$EXPORT_DIR/${{ matrix.path }}/${{ matrix.exportName }}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: build/${{ matrix.path }}
